general.import = [ "~/.config/omarchy/current/theme/alacritty.toml" ]

[env]
TERM = "xterm-256color"

[font]
# normal = { family = "CaskaydiaMono Nerd Font" }
# bold = { family = "CaskaydiaMono Nerd Font" }
# italic = { family = "CaskaydiaMono Nerd Font" }
normal = { family = "CaskaydiaMono Nerd Font" }
bold = { family = "CaskaydiaMono Nerd Font" }
italic = { family = "CaskaydiaMono Nerd Font" }
size = 9
#screenrecording
# size = 15

[window]
padding.x = 1
padding.y = 1
decorations = "None"
opacity = 0.98

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" }
]
