tap "adoptopenjdk/openjdk"
tap "coursier/formulas"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "minio/stable"
tap "osx-cross/arm"
tap "osx-cross/avr"
tap "qmk/qmk"
tap "scalacenter/bloop"
brew "bash-completion"
brew "commitizen"
brew "docker", link: false
brew "docker-machine"
brew "hub"
brew "hugo"
brew "neovim", args: ["HEAD"]
brew "node"
brew "okteto", link: false
brew "pandoc"
brew "postgresql", restart_service: true
brew "python@3.8", link: true
brew "sbt"
brew "scala"
brew "tig"
brew "tmux"
brew "tree"
brew "wget"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "minio/stable/mc"
brew "minio/stable/minio"
brew "qmk/qmk/qmk"
cask "adoptopenjdk11"
cask "istat-menus"
cask "mark-text"
