tap "adoptopenjdk/openjdk"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "minio/stable"
tap "osx-cross/arm"
tap "osx-cross/avr"
tap "qmk/qmk"
brew "bash-completion"
brew "docker", link: false
brew "docker-machine"
brew "hugo"
brew "neovim"
brew "pandoc"
brew "python@3.8", link: true
brew "tmux"
brew "wget"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "minio/stable/mc"
brew "minio/stable/minio"
brew "qmk/qmk/qmk"
cask "adoptopenjdk11"
cask "mark-text"
