[manager]
prepend_keymap = [
	{ on = "?", run = 'help', desc = "Help" },
]

# keymap = [

# 	# Help
# 	{ on = [ "?" ], exec = "help", desc = "Open help" },
# ]

# [tasks]

# keymap = [
# 	{ on = [ "?" ], exec = "help", desc = "Open help" }
# ]

# [select]

# keymap = [
# 	{ on = [ "?" ], exec = "help", desc = "Open help" }
# ]

# [input]

# keymap = [
# 	# Help
# 	{ on = [ "?" ], exec = "help", desc = "Open help" }
# ]

# [completion]

# keymap = [
# 	{ on = [ "?" ], exec = "help", desc = "Open help" }
# ]

