[manager]
prepend_keymap = [
	{ on = "?", run = 'help', desc = "Help" },
	# { on = "sr", run = 'S', desc = "fuzzy search ripgrep" },
]

[help]
prepend_keymap = [
	{ on = "/", run = 'filter', desc = "Filter" },
]
# keymap = [

# 	# Help
# 	{ on = [ "?" ], exec = "help", desc = "Open help" },
# ]

# [tasks]

# keymap = [
# 	{ on = [ "?" ], exec = "help", desc = "Open help" }
# ]

# [select]

# keymap = [
# 	{ on = [ "?" ], exec = "help", desc = "Open help" }
# ]

# [input]

# keymap = [
# 	# Help
# 	{ on = [ "?" ], exec = "help", desc = "Open help" }
# ]

# [completion]

# keymap = [
# 	{ on = [ "?" ], exec = "help", desc = "Open help" }
# ]

