return {
  {}
  -- {
  --   "3rd/image.nvim",
  --   priority = 1000, -- Ensure it loads early
  --   -- ft = { "markdown" },
  --   config = function()
  --     require("image").setup({
  --       backend = "kitty",
  --     })
  --   end
  -- }
  -- { --for Mermaid diagrams: need image, imagemagick and many other
  --   "3rd/diagram.nvim",
  --   event = "VeryLazy",
  --   ft = { "markdown" },
  --   dependencies = {
  --     "3rd/image.nvim",
  --   },
  --   opts = { -- you can just pass {}, defaults below
  --     renderer_options = {
  --       mermaid = {
  --         background = "transparent", -- nil | "transparent" | "white" | "#hex"
  --         theme = nil,                -- nil | "default" | "dark" | "forest" | "neutral"
  --         scale = 1,                  -- nil | 1 (default) | 2  | 3 | ...
  --       },
  --       plantuml = {
  --         charset = nil,
  --       },
  --       d2 = {
  --         theme_id = nil,
  --         dark_theme_id = nil,
  --         scale = nil,
  --         layout = nil,
  --         sketch = nil,
  --       },
  --     }
  --   },
  -- }
}
