import QtQuick
import qs.Commons
import "../plugins/io.github.sirjul1337.lock-explorer/designs"

// Generated by omarchy-lock-explorer from a custom layout (my-boot). Its boot
// screen twin comes from the same layout.conf.
DesignBase {
  id: lock
  inputItem: field.input

  Rectangle { anchors.fill: parent; color: Color.background }

  MouseArea {
    anchors.fill: parent
    hoverEnabled: true
    onClicked: { lock.wakeRequested(); lock.forcePasswordFocus() }
    onPositionChanged: lock.wakeRequested()
  }

  Column {
    anchors.horizontalCenter: parent.horizontalCenter
    anchors.top: parent.top
    anchors.topMargin: Math.round(lock.height * 18 / 100)
    spacing: 4
    Text {
      anchors.horizontalCenter: parent.horizontalCenter
      text: Qt.formatTime(lock.now, "HH:mm")
      color: Color.lock.text
      font.family: Style.font.family
      font.pixelSize: Math.round(Style.font.baseSize * 7)
      font.weight: Font.Light
    }
    Text {
      anchors.horizontalCenter: parent.horizontalCenter
      text: "Omarchy Linux"
      color: Color.lock.text
      font.family: Style.font.family
      font.pixelSize: Style.font.display
    }
    Text {
      anchors.horizontalCenter: parent.horizontalCenter
      text: "ssp-tux"
      color: lock.withAlpha(Color.lock.text, 0.6)
      font.family: Style.font.family
      font.pixelSize: Style.font.bodySmall
    }
  }

  PasswordField {
    id: field
    lock: lock
    anchors.horizontalCenter: parent.horizontalCenter
    y: Math.round(lock.height * 72 / 100) - height / 2
    width: 400
    height: 54
    radius: 0
    placeholder: "Password"
  }
}
