[colors]
foreground=ddf7ff
background=0B0C16
selection-foreground=0B0C16
selection-background=ddf7ff

regular0=0B0C16
regular1=50f872
regular2=4fe88f
regular3=50f7d4
regular4=829dd4
regular5=86a7df
regular6=7cf8f7
regular7=85E1FB

bright0=6a6e95
bright1=85ff9d
bright2=9cf7c2
bright3=a4ffec
bright4=c4d2ed
bright5=cddbf4
bright6=d1fffe
bright7=ddf7ff
