auto_bcc = "sspaeti@hey.com"

[[accounts]]
  name = "Personal"
  imap = "imap.mail.hostpoint.ch:993"
  smtp = "asmtp.mail.hostpoint.ch:587"
  user = "simu@sspaeti.com"
  password = "$IMAP_PASS_SIMU"
  from = "Simon Späti <simu@sspaeti.com>"
  starttls = false

[[accounts]]
  name = "Work"
  imap = "imap.mail.hostpoint.ch:993"
  smtp = "asmtp.mail.hostpoint.ch:587"
  user = "simon@sspaeti.com"
  password = "$IMAP_PASS_SIMON"
  from = "Simon Späti <simon@ssp.sh>"
  starttls = false

[[accounts]]
  name = "Work Info"
  imap = "imap.mail.hostpoint.ch:993"
  smtp = "asmtp.mail.hostpoint.ch:587"
  user = "info@ssp.sh"
  password = "$IMAP_PASS_SSP_INFO"
  from = "SSP Data GmbH <info@ssp.sh>"
  starttls = false

[[senders]]
  name = "Simon Späti" #alias for s with simu
  from = "Simon Späti <s@ssp.sh>"
  account = "Personal"

[screener]
  screened_in = "/home/sspaeti/.dotfiles/mutt/.lists/screened_in.txt"
  screened_out = "/home/sspaeti/.dotfiles/mutt/.lists/screened_out.txt"
  feed = "/home/sspaeti/.dotfiles/mutt/.lists/feed.txt"
  papertrail = "/home/sspaeti/.dotfiles/mutt/.lists/papertrail.txt"
  spam = "/home/sspaeti/.dotfiles/mutt/.lists/spam.txt"

[folders]
  inbox = "INBOX"
  sent = "Sent"
  trash = "Trash"
  drafts = "Drafts"
  to_screen = "ToScreen"
  feed = "Feed"
  papertrail = "PaperTrail"
  screened_out = "ScreenedOut"
  archive = "Archive"
  work = "Work"
  waiting = "Waiting"
  scheduled = "Scheduled"
  someday = "Someday"
  spam = "spam"
  tab_order = ["inbox", "to_screen", "feed", "papertrail", "waiting", "someday", "scheduled", "sent", "work", "archive", "screened_out", "trash"]

[ui]
  theme = "dark"
  inbox_count = 200
  signature   = """**Simon Späti**
Data Engineer & Technical Author, SSP Data GmbH

Connect: [LinkedIn](https://li.ssp.sh/) | [Bluesky](https://bs.ssp.sh/) | [GitHub](https://gh.ssp.sh/)
Explore: [Website](https://ssp.sh/) | [Vault](https://vault.ssp.sh/) | [Book](https://dedp.online/) | [Services](https://ssp.sh/services)

*sent from [neomd](https://neomd.ssp.sh)*"""
